repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks-docker
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: zricethezav/gitleaks protect
        language: docker_image
  - repo: local
    hooks:
      - id: ledger-add
        name: Ledger add
        entry: ledger-add.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: ledger-finalize
        name: Ledger finalize
        entry: ledger-finalize.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [post-commit]
      - id: prevent-commits-to-default-branch
        name: Prevent commits to default branch
        entry: ./prevent-commits-to-default-branch.sh
        language: script
        pass_filenames: false
        always_run: true
